name: scanner
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.4 #網路框架
  shared_preferences: ^2.0.11 #本地緩存
  fluttertoast: ^8.0.8 #toast,由裝置下方出現的提示信息
  flutter_redux: ^0.8.2 #redux架構
  device_info: ^2.0.3 #設備信息
  network_info_plus: ^2.1.2 #網路連接
  json_annotation: ^4.4.0 #json模板
  url_launcher: ^6.0.17 #啟動外部瀏覽器
  flutter_spinkit: ^5.1.0 #loading框樣式
  path_provider: ^2.0.8 #本地路徑
  permission_handler: ^8.3.0 #權限
  scoped_model: ^1.1.0 #狀態管理和共享
  event_bus: ^2.0.0 #事件管理
  intl: ^0.17.0 #時間格式化
  auto_size_text: ^3.0.0 #字體縮放
  flutter_screenutil: ^5.1.0 #固定字體大小，不被裝置系統字體影響
  pointycastle: ^3.5.0 #加解密機制pacs7 , aes ...
  font_awesome_flutter: ^9.2.0 #flutter圖案
  android_intent: ^2.0.2 #可以取得安卓系統資料
  keyboard_actions: ^3.4.6 #鍵盤action
  wifi_iot: ^0.3.12 #選擇wifi
  share_plus: ^3.0.4 #share
  image_picker: ^0.8.4+4  #拍手機畫面
  reorderables: ^0.4.2 #拖動
  reorderable_grid_view: ^2.2.2 #拖動grid
  file_picker: ^4.3.1 #存取檔案
  cached_network_image: ^3.2.0 #cach image
  animated_floating_buttons: ^0.0.2 #動態按鈕
  connectivity: ^3.0.6 #網路
  angles: ^2.1.1 #畫動畫
  ele_progress: ^0.0.1 #進度條動畫
  flutter_archive: ^4.1.1 #zip
  extended_image: ^6.0.1 #圖片編輯器，擴充image套件
  image_editor: ^1.0.2 #圖片編輯器
  image: ^3.1.1 #圖片編輯器
  xml: ^5.3.1 #xml解析
  photo_view: ^0.13.0 # 滑動圖片
  encrypt: ^5.0.1 #aes
  dropdown_search: ^2.0.1 #下拉選單
  pdf: ^3.7.4 #pdf
  # libdsm: #smb
  #   path: ../libdsm/libdsm_flutter/libdsm
  smblib:
    path: ../smblib/


dev_dependencies:
  json_serializable: ^6.1.3 #json模板
  build_runner: ^1.5.0
  flutter_launcher_icons: ^0.9.2 #產生icon
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - static/images/scan.png
    - static/images/wifi.png
    - static/images/connect.png
    - static/images/icon.jpg
    - static/images/icon2.jpg
    - static/images/printImg.jpg
    - static/images/navBar.png
    - static/images/file.png
    - static/images/document.png
    - static/images/fileData.png
    - static/images/arrow.png
    - static/images/backgroud.png
    - static/images/bg.png
    - static/images/ccs.png
    - static/images/connection.png
    - static/images/Ellipse.png
    - static/images/fuctionSelect.png
    - static/images/loginBtn.png
    - static/images/login_ok.png
    - static/images/logo.png
    - static/images/message.png
    - static/images/password_field.png
    - static/images/rotate90.png
    - static/images/scannerSet.png
    - static/images/search.png
    - static/images/settings_1.png
    - static/images/settings.png
    - static/images/uploadCloud.png
    - static/images/wifiSet.png
    - static/images/yellowBtn.png
    - static/images/logout.png
    - static/images/trash.png
    - static/images/scanBtn.png
    - static/images/outside.png
    - static/images/dropdown.png


flutter_icons:
  image_path: "static/images/ic_launcher.png"
  android: "launcher_icon" # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
